
server:
  port: 8703
eureka:
  instance:
    instance-id: trying:discovery-client:test003 #发现客户端的实例id
    prefer-ip-address: true      #false 表示使用主机名进行地址访问；true表示根据IP进行地址重定向
  client:
    serviceUrl:
      defaultZone: http://localhost:8803/eureka/,http://localhost:8802/eureka/,http://localhost:8801/eureka/
